import { UserProfile, EncounterCard, MatchEntry, ChatMessage, StampEntry, TokuHistoryEntry } from './types';

const mockUsers: UserProfile[] = [
  {
    id: 'u1',
    name: 'Sakura',
    nationality: 'JP',
    gender: 'Female',
    birthDate: '1998-03-15',
    ageGroup: '20s',
    hobbyTags: ['Anime', 'Cosplay', 'K-POP', 'Karaoke'],
    freeText: 'Demon Slayer, Rengoku, Hoshi no Rin',
    videoLinks: [],
    languages: ['Japanese', 'English'],
    travelStyle: 'Sightseeing',
    genderFilter: ['No preference'],
    ageRangeMin: 18,
    ageRangeMax: 35,
    tokuPoints: 350,
    avatarUrl: '',
    wantToMeetMode: true,
  },
  {
    id: 'u2',
    name: 'Alex',
    nationality: 'US',
    gender: 'Male',
    birthDate: '1995-07-22',
    ageGroup: '20s',
    hobbyTags: ['EDM', 'Club', 'Game', 'Sauna'],
    freeText: 'Final Fantasy, EDM festivals, Techno',
    videoLinks: [],
    languages: ['English', 'Spanish'],
    travelStyle: 'Adventure',
    genderFilter: ['No preference'],
    ageRangeMin: 20,
    ageRangeMax: 40,
    tokuPoints: 150,
    avatarUrl: '',
    wantToMeetMode: true,
  },
  {
    id: 'u3',
    name: 'Min-ji',
    nationality: 'KR',
    gender: 'Female',
    birthDate: '2000-11-03',
    ageGroup: '20s',
    hobbyTags: ['K-POP', 'Cosmetics', 'Karaoke', 'Female Idol'],
    freeText: 'BTS, BLACKPINK, Makeup lover',
    videoLinks: [],
    languages: ['Korean', 'English', 'Japanese'],
    travelStyle: 'Shopping',
    genderFilter: ['No preference'],
    ageRangeMin: 18,
    ageRangeMax: 30,
    tokuPoints: 620,
    avatarUrl: '',
    wantToMeetMode: true,
  },
  {
    id: 'u4',
    name: 'Luca',
    nationality: 'IT',
    gender: 'Male',
    birthDate: '1993-05-18',
    ageGroup: '30s',
    hobbyTags: ['Bar/Izakaya', 'Jazz', 'Hiking'],
    freeText: 'Wine tasting, Jazz nights, Mountain trails',
    videoLinks: [],
    languages: ['Italian', 'English', 'French'],
    travelStyle: 'Gourmet',
    genderFilter: ['No preference'],
    ageRangeMin: 20,
    ageRangeMax: 45,
    tokuPoints: 80,
    avatarUrl: '',
    wantToMeetMode: true,
  },
  {
    id: 'u5',
    name: 'Mei',
    nationality: 'TW',
    gender: 'Female',
    birthDate: '1999-09-12',
    ageGroup: '20s',
    hobbyTags: ['Anime', 'Manga', 'J-POP', 'Cosplay'],
    freeText: 'One Piece, Demon Slayer, Ado',
    videoLinks: [],
    languages: ['Chinese', 'Japanese', 'English'],
    travelStyle: 'Culture',
    genderFilter: ['No preference'],
    ageRangeMin: 18,
    ageRangeMax: 35,
    tokuPoints: 1050,
    avatarUrl: '',
    wantToMeetMode: true,
  },
];

export const mockEncounterCards: EncounterCard[] = [
  {
    id: 'e1',
    user: mockUsers[0],
    location: 'Near Shibuya Station',
    encounteredAt: new Date(Date.now() - 8 * 60000).toISOString(),
    minutesAgo: 8,
    matchingTags: ['Anime', 'K-POP'],
    matchingWords: ['Demon Slayer'],
    distance: 30,
  },
  {
    id: 'e2',
    user: mockUsers[1],
    location: 'Near Shinjuku Station',
    encounteredAt: new Date(Date.now() - 15 * 60000).toISOString(),
    minutesAgo: 15,
    matchingTags: ['EDM'],
    matchingWords: [],
    distance: 45,
  },
  {
    id: 'e3',
    user: mockUsers[2],
    location: 'Near Harajuku Station',
    encounteredAt: new Date(Date.now() - 22 * 60000).toISOString(),
    minutesAgo: 22,
    matchingTags: ['K-POP', 'Karaoke'],
    matchingWords: ['BTS'],
    distance: 20,
  },
  {
    id: 'e4',
    user: mockUsers[3],
    location: 'Near Roppongi Station',
    encounteredAt: new Date(Date.now() - 45 * 60000).toISOString(),
    minutesAgo: 45,
    matchingTags: [],
    matchingWords: [],
    distance: 50,
  },
  {
    id: 'e5',
    user: mockUsers[4],
    location: 'Near Akihabara Station',
    encounteredAt: new Date(Date.now() - 12 * 60000).toISOString(),
    minutesAgo: 12,
    matchingTags: ['Anime', 'Manga', 'Cosplay'],
    matchingWords: ['Demon Slayer', 'One Piece'],
    distance: 15,
  },
];

export const mockMatches: MatchEntry[] = [
  {
    id: 'm1',
    user: mockUsers[0],
    matchedAt: new Date(Date.now() - 30 * 60000).toISOString(),
    status: 'matched',
    chatOpen: true,
  },
  {
    id: 'm2',
    user: mockUsers[2],
    matchedAt: new Date(Date.now() - 60 * 60000).toISOString(),
    status: 'matched',
    chatOpen: true,
  },
  {
    id: 'm3',
    user: mockUsers[1],
    matchedAt: new Date().toISOString(),
    status: 'pending_received',
    chatOpen: false,
  },
];

export const mockMessages: ChatMessage[] = [
  { id: 'msg1', senderId: 'u1', text: 'Hi! I saw we both love Demon Slayer!', timestamp: new Date(Date.now() - 25 * 60000).toISOString() },
  { id: 'msg2', senderId: 'me', text: 'Yes! Rengoku is the best!', timestamp: new Date(Date.now() - 24 * 60000).toISOString() },
  { id: 'msg3', senderId: 'u1', text: 'Want to grab a coffee nearby?', timestamp: new Date(Date.now() - 20 * 60000).toISOString() },
  { id: 'msg4', senderId: 'me', text: 'Sure! How about the cafe near Shibuya?', timestamp: new Date(Date.now() - 18 * 60000).toISOString() },
];

export const mockStamps: StampEntry[] = [
  { id: 's1', nationality: 'JP', flag: '\u{1F1EF}\u{1F1F5}', userName: 'Sakura', date: '2024-01-15', location: 'Shibuya' },
  { id: 's2', nationality: 'KR', flag: '\u{1F1F0}\u{1F1F7}', userName: 'Min-ji', date: '2024-01-20', location: 'Harajuku' },
  { id: 's3', nationality: 'US', flag: '\u{1F1FA}\u{1F1F8}', userName: 'Alex', date: '2024-02-03', location: 'Shinjuku' },
  { id: 's4', nationality: 'FR', flag: '\u{1F1EB}\u{1F1F7}', userName: 'Pierre', date: '2024-02-10', location: 'Asakusa' },
  { id: 's5', nationality: 'TH', flag: '\u{1F1F9}\u{1F1ED}', userName: 'Nong', date: '2024-02-18', location: 'Ikebukuro' },
  { id: 's6', nationality: 'AU', flag: '\u{1F1E6}\u{1F1FA}', userName: 'Emma', date: '2024-03-01', location: 'Ueno' },
];

export const mockTokuHistory: TokuHistoryEntry[] = [
  { id: 't1', action: 'Met someone', points: 30, date: '2024-03-01' },
  { id: 't2', action: 'First meeting with Australian', points: 20, date: '2024-03-01' },
  { id: 't3', action: 'Met someone', points: 30, date: '2024-02-18' },
  { id: 't4', action: 'Profile completed', points: 10, date: '2024-01-10' },
];

export const mockMyProfile: UserProfile = {
  id: 'me',
  name: 'Taro',
  nationality: 'JP',
  gender: 'Male',
  birthDate: '1997-06-20',
  ageGroup: '20s',
  hobbyTags: ['Anime', 'K-POP', 'EDM', 'Manga', 'Cosplay'],
  freeText: 'Demon Slayer, One Piece, BTS, EDM lover',
  videoLinks: ['https://youtube.com/watch?v=example1'],
  languages: ['Japanese', 'English'],
  travelStyle: 'Adventure',
  genderFilter: ['No preference'],
  ageRangeMin: 18,
  ageRangeMax: 40,
  tokuPoints: 290,
  avatarUrl: '',
  wantToMeetMode: true,
};
